Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DXWebApplication1.Models

    Partial Public Class Nwind_SalesDataEntities
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=Nwind_SalesDataEntities")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Overridable Property SalesPersons() As DbSet(Of SalesPerson)
    End Class
End Namespace
